[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.3.1"
  HUGO_VERSION = "0.77.0"

[build]
  command = "npm run build"
  publish = "dist"

[build.processing.images]
  compress = true

[context.deploy-preview]
  command = "npm run build:preview"

[context.production.environment]
  HUGO_ENV = "production"
  DEPLOY_PRIME_URL = "https://publications.osteopathes.pro/"

[[redirects]]
  from = "/fr/jeux/cas-cliniques/01-fan-de-yoga"
  to = "/fr/jeux/cas-cliniques/01-fan-de-yoga/"
  status = 301
  force = true
