[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12.19.0"
  NPM_VERSION = "6.14.7"
  HUGO_VERSION = "0.76.5"

[build]
  command = "npm run build"
  publish = "dist"

[build.processing.images]
  compress = true

[context.deploy-preview]
  command = "npm run build:preview"

[context.production.environment]
  HUGO_ENV = "production"
  DEPLOY_PRIME_URL = "https://publications.osteopathes.pro/"
