[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.69.0"

[build]
  command = "npm run build"
  publish = "dist"

[build.processing.images]
  compress = true

[context.deploy-preview]
  command = "npm run build:preview"

[context.production.environment]
  HUGO_ENV = "production"
  DEPLOY_PRIME_URL = "https://publications.osteopathes.pro/"
