DefaultContentLanguage: fr
baseURL: http://localhost:3000/
defaultContentLanguageInSubdir: true
languageCode: "fr"
copyright: "Cette œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International. https://creativecommons.org/licenses/by-nc-sa/4.0/"

author:
  name: "Auteurs d'ostéopathes.pro"

markup:
  goldmark:
    renderer:
      unsafe: true

  tableOfContents:
    endLevel: 3
    startLevel: 2
    ordered: false

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds: ["RSS", "taxonomyTerm"]
# enableGitInfo: true

frontmatter:
  date:
    - publishDate
    - date
    - :fileModTime
  publishDate:
    - publishDate
    - date
    - :fileModTime

params:
  description: "Articles et dossiers sur l'ostéopathie ainsi que les actualités d'osteopathes.pro: démographie ostéopathes, ateliers rgpd etc."
  editeur:
    name: "osteopathes.pro"

languages:
  fr:
    contentDir: content/fr
    languageName: Français
    title: "osteopathes.pro – Publications"
    weight: 1

    permalinks:
      actualites: /fr/:sections/:year/:month/:slug
      articles: /fr/:sections/:year/:month/:slug
      dossiers: /fr/:sections/:slug

    taxonomies:
      auteur: "auteurs"
      label: "labels"
      catégorie: "catégories"
