DefaultContentLanguage: fr
baseURL: http://localhost:3000/
defaultContentLanguageInSubdir: true
languageCode: "fr"
copyright: "Cette œuvre est mise à disposition selon les termes de la Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International. https://creativecommons.org/licenses/by-nc-sa/4.0/"

author:
  name: "Auteurs d'Ostéopathes.pro"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds: ["RSS", "taxonomyTerm"]
# enableGitInfo: true

frontmatter:
  date:
    - publishDate
    - date
    - :fileModTime
  publishDate:
    - publishDate
    - date
    - :fileModTime

params:
  description: "Articles et dossiers sur l'ostéopathie en général et les nouveautés du site osteopathes.pro."
  editeur:
    name: "Osteopathes.pro"

languages:
  fr:
    contentDir: content/fr
    languageName: Français
    title: "Ostéopathes.pro – Publications"
    weight: 1

    permalinks:
      actualites: /fr/:sections/:year/:month/:slug
      articles: /fr/:sections/:year/:month/:slug
      dossiers: /fr/:sections/:title

    taxonomies:
      auteur: "auteurs"
      label: "labels"
      catégorie: "catégories"

